artifact_location: file:////content/drive/MyDrive/Labmentix projects /EMI Predictions/content/mlruns/639353525708722948
creation_time: 1771468096302
experiment_id: '639353525708722948'
last_update_time: 1771468096302
lifecycle_stage: active
name: EMI_Classification_Experiment
