artifact_uri: file:////content/drive/MyDrive/Labmentix projects /EMI Predictions/content/mlruns/639353525708722948/9eb01ab37b354c488e21c5b8cc0cfd37/artifacts
end_time: 1771468251546
entry_point_name: ''
experiment_id: '639353525708722948'
lifecycle_stage: active
run_id: 9eb01ab37b354c488e21c5b8cc0cfd37
run_name: XGBClassifier_Run
run_uuid: 9eb01ab37b354c488e21c5b8cc0cfd37
source_name: ''
source_type: 4
source_version: ''
start_time: 1771468247048
status: 3
tags: []
user_id: root
