aliases: []
creation_timestamp: 1771468819347
current_stage: None
description: null
last_updated_timestamp: 1771468819347
name: EMI_Classifier_Best
run_id: bb4e1b4bcb7f408db80b53c8f529c596
run_link: null
source: file:////content/drive/MyDrive/Labmentix projects /EMI Predictions/content/mlruns/762983407233689605/bb4e1b4bcb7f408db80b53c8f529c596/artifacts/models
status: READY
status_message: null
storage_location: file:////content/drive/MyDrive/Labmentix projects /EMI Predictions/content/mlruns/762983407233689605/bb4e1b4bcb7f408db80b53c8f529c596/artifacts/models
user_id: null
version: 1
